name: dart_version_switcher
version: 1.0.1
description: A Dart package for switching Dart versions using Homebrew.

executables:
  dart_version_switcher: dart_version_switcher.dart

repository: https://github.com/Jesse-Dan

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
